apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synmedia-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: synmedia-nfs
  resources:
    requests:
      storage: 10Ti
