apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-retain-rwo
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-configs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-retain-rwo
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-logs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-retain-rwo
  resources:
    requests:
      storage: 1Gi
