apiVersion: v1
kind: Namespace
metadata:
  labels:
    homelab.local/category: apps
    homelab.local/data: files
    homelab.local/exposure: lan
    homelab.local/login: authentik-oidc
  name: booklore
