apiVersion: v1
kind: Secret
metadata:
  name: babybuddy-mcp-secrets
  namespace: babybuddy-mcp
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
data:
  AUTHENTIK_CLIENT_ID: ${BABYBUDDY_MCP_SECRETS_AUTHENTIK_CLIENT_ID}
  AUTHENTIK_CLIENT_SECRET: ${BABYBUDDY_MCP_SECRETS_AUTHENTIK_CLIENT_SECRET}
  BABYBUDDY_API_TOKEN: ${BABYBUDDY_MCP_SECRETS_BABYBUDDY_API_TOKEN}
  MCP_AUTH_TOKEN: ${BABYBUDDY_MCP_SECRETS_MCP_AUTH_TOKEN}
