apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    homelab.local/category: services
    homelab.local/data: files
    homelab.local/exposure: cluster
  name: mqtt
spec:
  finalizers:
  - kubernetes
