apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app: noip-duc
    homelab.local/category: system
  name: noip-duc
spec:
  finalizers:
  - kubernetes
