apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    homelab.local/category: services
    homelab.local/data: files
    homelab.local/exposure: cluster
    homelab.local/login: none
  name: redis-ha
spec:
  finalizers:
  - kubernetes
