apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    homelab.local/category: system
    name: cert-manager
  name: cert-manager
spec:
  finalizers:
  - kubernetes
