apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    homelab.local/category: system
    homelab.local/data: stateless
    homelab.local/exposure: cluster
  name: metallb-system
spec:
  finalizers:
  - kubernetes
