apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    homelab.local/category: system
    name: metallb-system
  name: metallb-system
spec:
  finalizers:
  - kubernetes
