apiVersion: v1
kind: Namespace
metadata:
  labels:
    homelab.local/category: services
    homelab.local/data: stateless
    homelab.local/exposure: cluster
    homelab.local/login: none
  name: smtp-relay
