apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: emby-media
  namespace: emby
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  storageClassName: nfs-retain-rwo
  volumeMode: Filesystem
  volumeName: emby-media-pv
