additionalVolumeMounts:
- mountPath: /mnt/synmedia
  name: emby-media
  readOnly: false
additionalVolumes:
- name: emby-media
  persistentVolumeClaim:
    claimName: emby-media
affinity: {}
env:
  PGID: "999"
  PUID: "1027"
  TZ: ${TIMEZONE}
image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: linuxserver/emby
  tag: version-4.9.1.90
ingress:
  enabled: false
livenessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 60
  path: /emby/System/Ping
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
nodeSelector: {}
persistence:
  annotations: {}
  enabled: true
  mountPath: /config
  size: 10Gi
  storageClass: nfs-retain-rwo
podSecurityContext:
  fsGroup: 999
readinessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 60
  path: /emby/System/Ping
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
replicaCount: 1
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 250m
    memory: 512Mi
service:
  httpPort: 8096
  httpsPort: 8920
  type: ClusterIP
startupProbe:
  enabled: true
  failureThreshold: 30
  initialDelaySeconds: 0
  path: /emby/System/Ping
  periodSeconds: 10
  timeoutSeconds: 5
tolerations: []
