"""Header comment for the files the tool writes for Flux (CRs and
kustomizations).

The header marks a file as generated, so it isn't hand-edited. It has no
timestamp: a date in the file would make it change on every run that touches
it, giving a diff with nothing to review. git records when each file
changed. `docs/inventory.md` (gitignored) and the top-level `README.md`'s
"last capture" line still record when a capture ran.
"""

from __future__ import annotations

_FIRST_LINE = "# Generated by k8s-backup-repo-gen.\n"
_FIXED_SECOND_LINE = "# Do not hand-edit; this file is overwritten on the next run.\n"


def generated_header(*, extra_lines: list[str] | None = None) -> str:
    lines = [_FIRST_LINE.rstrip("\n"), _FIXED_SECOND_LINE.rstrip("\n")]
    if extra_lines:
        lines.extend(f"# {line}" for line in extra_lines)
    return "\n".join(lines) + "\n"
