"""Header comment for generated Flux CRs and kustomizations (task spec section 1).

The header records "the ISO-8601 timestamp of generation," but the task
also requires that re-running against an unchanged cluster produce zero
unexpected diffs (success criterion 6). Those two requirements only agree
if "generation" means the last time this file's actual content changed,
not the last time the script happened to run. So the timestamp is sticky:
when a file's rendered body is byte-identical to what's already on disk,
the old timestamp is kept; it only advances when the content really did
change. `docs/inventory.md` and the top-level `README.md`'s "last capture"
line intentionally do NOT use this -- they're point-in-time snapshots
(task spec section 8), so their timestamp is meant to always reflect the
most recent run, confirming the backup was actually re-verified.
"""

from __future__ import annotations

from pathlib import Path

_PREFIX = "# Generated by k8s-backup-repo-gen on "
_FIXED_SECOND_LINE = "# Do not hand-edit; this file is overwritten on the next run.\n"


def header_rest(extra_lines: list[str] | None = None) -> str:
    """Everything in the header block after the timestamp line."""
    lines = [_FIXED_SECOND_LINE.rstrip("\n")]
    if extra_lines:
        lines.extend(f"# {line}" for line in extra_lines)
    return "\n".join(lines) + "\n"


def stable_timestamp(path: Path, new_rest_plus_body: str, run_timestamp: str) -> str:
    """The timestamp to use for this write: kept from disk if content is unchanged."""
    if not path.exists():
        return run_timestamp
    try:
        existing = path.read_text(encoding="utf-8")
    except OSError:
        return run_timestamp
    first, sep, rest = existing.partition("\n")
    if not sep or not first.startswith(_PREFIX):
        return run_timestamp
    old_timestamp = first[len(_PREFIX) :].rstrip(".")
    if rest == new_rest_plus_body:
        return old_timestamp
    return run_timestamp


def full_header(timestamp: str, rest: str) -> str:
    return f"{_PREFIX}{timestamp}.\n{rest}"


def generated_header(timestamp: str, *, extra_lines: list[str] | None = None) -> str:
    """Non-sticky header for callers that don't go through Sink's stable-header path."""
    return full_header(timestamp, header_rest(extra_lines))
