"""Builders for docs/inventory.md, docs/secrets-inventory.csv, docs/sops-planning.md
(task spec sections 5 and 8).
"""

from __future__ import annotations

import csv
import io


def build_secrets_csv(rows: list[dict]) -> str:
    buf = io.StringIO()
    writer = csv.DictWriter(
        buf, fieldnames=["namespace", "name", "type", "keys", "created"], lineterminator="\n"
    )
    writer.writeheader()
    for row in rows:
        writer.writerow(row)
    return buf.getvalue()


def build_sops_planning_md(rows: list[dict], timestamp: str) -> str:
    lines = [
        "# SOPS planning",
        "",
        f"Generated {timestamp}. One checklist item per secret in "
        "`docs/secrets-inventory.csv`. For each, decide: encrypt in git with "
        "SOPS, manage with an external-secrets operator, or regenerate on "
        "install (e.g. a randomly-generated internal password).",
        "",
        "No secret values are captured anywhere in this repo. This file "
        "tracks metadata and a disposition decision only.",
        "",
    ]
    if not rows:
        lines.append("No secrets matched the inventory filter (see task spec section 5).")
        return "\n".join(lines) + "\n"

    for row in rows:
        lines.append(f"- [ ] `{row['namespace']}/{row['name']}` ({row['type']}, keys: {row['keys'] or 'none'})")
        lines.append("      Disposition: TODO (sops-in-git / external-secrets / regenerate-on-install)")
    return "\n".join(lines) + "\n"


IP_INVENTORY_FIELDNAMES = ["ip", "classification", "purpose", "file", "occurrences", "field_paths"]


def build_ip_inventory_csv(rows: list[dict]) -> str:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=IP_INVENTORY_FIELDNAMES, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow(row)
    return buf.getvalue()


def build_variable_substitutions_md(substitutions: list[dict]) -> str:
    """Git-tracked schema doc: which ${PLACEHOLDER}s exist and what tier
    they're in, WITHOUT the literal values (those live only in the
    gitignored kubernetes/.local/variable-substitutions.yaml). Lets a
    future restore know what to create on the cluster even without access
    to the current operator's local files.
    """
    lines = [
        "# Variable substitutions",
        "",
        "Placeholders that appear in git-tracked files under `kubernetes/cluster/` "
        "(and possibly elsewhere), resolved at apply time by Flux's "
        "`postBuild.substituteFrom` on `kubernetes/flux/config/cluster-resources.yaml` -- "
        "see https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution. "
        "Real values are never in git; they live in the gitignored "
        "`kubernetes/.local/variable-substitutions.yaml`, and the ready-to-apply "
        "`kubernetes/.local/cluster-substitutions-configmap.yaml` / `-secret.yaml` rendered "
        "from it (regenerated by `capture`, never committed).",
        "",
        "To restore onto a fresh cluster (or one where the local files were lost): "
        "recreate a ConfigMap named `cluster-substitutions` and/or a Secret named "
        "`cluster-substitutions-secret`, both in `flux-system`, with the keys below.",
        "",
    ]
    if not substitutions:
        lines.append("None currently in use.")
        return "\n".join(lines) + "\n"

    lines.append("| Placeholder | Tier | Note |")
    lines.append("|---|---|---|")
    for s in sorted(substitutions, key=lambda s: s["placeholder"]):
        tier = "Secret" if s.get("sensitivity") == "secret" else "ConfigMap"
        lines.append(f"| `{s['placeholder']}` | {tier} | {s.get('note', '')} |")
    return "\n".join(lines) + "\n"


def build_redactions_md(redactions: list[str], timestamp: str) -> str:
    lines = [
        "# Redactions",
        "",
        f"Last capture run: {timestamp}.",
        "",
        "Every value this run's credential/secret scan (k8s_backup/secretscan.py) "
        "flagged before writing anything to disk. The value itself is never "
        "recorded here or anywhere else -- only where it was and why it was "
        "flagged, so this file is safe to commit.",
        "",
        "A redaction means the live cluster has a credential somewhere other "
        "than a Secret object (a command-line argument, an env var literal, an "
        "annotation, ...). Fix it at the source if you can (move it into a "
        "Secret + secretKeyRef); the redacted placeholder here just means the "
        "*generator* stopped short of writing the real value, not that the "
        "underlying exposure on the cluster is fixed.",
        "",
    ]
    if not redactions:
        lines.append("None this run.")
    else:
        for entry in redactions:
            lines.append(f"- {entry}")
    return "\n".join(lines) + "\n"


def build_inventory_md(data: dict) -> str:
    lines: list[str] = []
    a = lines.append

    a("# Cluster inventory")
    a("")
    a(f"Captured: {data['timestamp']}")
    a(f"Kube context: `{data['context']}`")
    a(f"Server version: `{data['server_version']}`")
    a("")

    a("## Nodes")
    a("")
    a("| Name | Roles | Version | OS |")
    a("|---|---|---|---|")
    for node in data["nodes"]:
        a(f"| {node['name']} | {node['roles']} | {node['version']} | {node['os']} |")
    a("")

    a("## Namespaces")
    a("")
    a(", ".join(f"`{n}`" for n in data["namespaces"]) or "(none)")
    a("")

    a("## Helm releases")
    a("")
    a("| Namespace | Release | Chart | Version | Revision | Status |")
    a("|---|---|---|---|---|---|")
    for r in data["releases"]:
        a(
            f"| {r['namespace']} | {r['release']} | {r['chart']} | "
            f"{r['chartVersion']} | {r['revision']} | {r['status']} |"
        )
    a("")

    a("## Helm repositories")
    a("")
    if data["helm_repos"]:
        a("| Name | URL |")
        a("|---|---|")
        for repo in data["helm_repos"]:
            a(f"| {repo['name']} | {repo['url']} |")
    else:
        a("(none configured)")
    a("")

    a("## PersistentVolumes")
    a("")
    if data["pvs"]:
        a("| Name | Capacity | Reclaim policy | StorageClass | Status |")
        a("|---|---|---|---|---|")
        for pv in data["pvs"]:
            a(
                f"| {pv['name']} | {pv['capacity']} | {pv['reclaim']} | "
                f"{pv['storageClass']} | {pv['phase']} |"
            )
    else:
        a("(none)")
    a("")

    a("## StorageClasses")
    a("")
    a("| Name | Provisioner | Reclaim policy | Default |")
    a("|---|---|---|---|")
    for sc in data["storageclasses"]:
        a(f"| {sc['name']} | {sc['provisioner']} | {sc['reclaim']} | {sc['is_default']} |")
    a("")

    a("## ClusterIssuers")
    a("")
    a(", ".join(f"`{c}`" for c in data["clusterissuers"]) or "(none)")
    a("")

    a("## MetalLB configuration")
    a("")
    if data["metallb_pools"]:
        for pool in data["metallb_pools"]:
            a(f"- IPAddressPool `{pool['namespace']}/{pool['name']}`: {', '.join(pool['addresses'])}")
    else:
        a("(no IPAddressPool objects found)")
    a("")

    a("## Custom Resource Definitions")
    a("")
    a(
        "All CRDs installed by operators/charts (there is no such thing as a "
        "\"system\" CRD in stock Kubernetes; every CRD here was installed by "
        "something running on this cluster):"
    )
    a("")
    for crd in data["crds"]:
        a(f"- `{crd['name']}` ({crd['group']}/{crd['version']})")
    a("")

    a("## IP addresses")
    a("")
    a(
        "Informational, not a pass/fail check: a homelab infra backup is "
        "expected to be full of its own private/RFC1918 addresses. A public "
        "address is treated as a real finding instead -- see "
        "`test_no_public_ip_addresses` in `scripts/tests/test_secrets_hygiene.py`. "
        "See `docs/ip-inventory.csv` for the full per-file breakdown with a "
        "best-effort guess at what each address is for."
    )
    a("")
    ip_rows = data.get("ip_inventory") or []
    public_rows = [r for r in ip_rows if r["classification"] == "public"]
    private_rows = [r for r in ip_rows if r["classification"] != "public"]
    if public_rows:
        a("**Public addresses found (review these):**")
        a("")
        for row in public_rows:
            a(f"- `{row['ip']}` -- seen in {row['occurrences']} file(s)")
        a("")
    a(f"Private/reserved addresses: {len(private_rows)} distinct address(es) found.")
    if private_rows:
        a("")
        for row in private_rows:
            a(f"- `{row['ip']}` ({row['classification']}) -- seen in {row['occurrences']} file(s)")
    a("")

    if data.get("warnings"):
        a("## Warnings from this capture run")
        a("")
        for w in data["warnings"]:
            a(f"- {w}")
        a("")

    return "\n".join(lines) + "\n"
