"""Static top-level scaffold files: README.md, .gitignore, .sops.yaml
(task spec section 7).
"""

from __future__ import annotations

_GITIGNORE = """\
# OS / editor cruft
.DS_Store
Thumbs.db
*.swp
*~
.vscode/
.idea/

# Python bytecode / test cache from scripts/ and scripts/tests/
__pycache__/
*.pyc
.pytest_cache/

# Backed up locally, never committed: built-in/system/operator-owned/
# dynamically-provisioned cluster resources (see skipfilter.py's
# classify_cluster_locality) and the operator's real variable-substitution
# mapping (varsub.py). Both are regenerated/maintained locally; committing
# either defeats the point (git would think it owns bootstrap-managed
# objects that change under a Kubernetes upgrade, or would leak the exact
# values variable substitution exists to keep out of git).
/kubernetes/.local/

# Raw non-Helm resource capture: local backup / staging area only, not the
# GitOps source of truth. Items get hand-curated into
# kubernetes/apps/<namespace>/<app>/ over time (see README's next-steps).
# Committing raw/ as-is means shipping cluster-generated cruft (uid,
# resourceVersion, internal service DNS, cluster IPs) that isn't
# re-appliable and isn't authoritative.
/kubernetes/raw/

# Never commit real SOPS age keys or other private key material
*.age
*.pem
*_rsa
*_ed25519
id_rsa*
id_ed25519*
"""

_SOPS_YAML = """\
# Scaffold only. This script never generates an age key (out of scope --
# see the task spec's non-goals). Replace the placeholder recipient below
# with your real age public key (`age-keygen -o age.agekey` run OUTSIDE
# this repo, keep age.agekey out of git) before encrypting anything with
# SOPS.
creation_rules:
  - path_regex: kubernetes/.*\\.sops\\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age1REPLACE-WITH-YOUR-REAL-AGE-PUBLIC-KEY
"""


_GITATTRIBUTES = """\
# Every file this script writes uses LF line endings, regardless of the
# platform it runs on (Python's `newline="\\n"` on write disables line-ending
# translation). Without this, a Windows git config with core.autocrlf=true
# rewrites everything to CRLF on checkout, which defeats the "re-running
# against an unchanged cluster produces zero diffs" property the generator
# is built around: every file would show as changed the moment git touches
# line endings.
* text=auto eol=lf
"""


def gitignore() -> str:
    return _GITIGNORE


def gitattributes() -> str:
    return _GITATTRIBUTES


_PRE_COMMIT_HOOK = """\
#!/bin/sh
# GitOps pre-commit gate: blocks the commit if scripts/tests/ (structure +
# secret-hygiene checks) doesn't pass. This is what stops a credential the
# generator's own redaction pass missed from reaching git history in the
# first place -- activate it once per clone with:
#   git config core.hooksPath .githooks
# Bypass only with `git commit --no-verify`, and only if you're certain.

set -e

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

PYTHON=""
for candidate in python3 python py; do
    # On Windows, `python`/`python3` on PATH can be a Microsoft Store
    # "app execution alias" stub that exists on disk (so `command -v`
    # finds it) but exits non-zero and prints a redirect message instead
    # of running -- confirm the candidate actually works, not just exists.
    if command -v "$candidate" >/dev/null 2>&1 && "$candidate" --version >/dev/null 2>&1; then
        PYTHON="$candidate"
        break
    fi
done

if [ -z "$PYTHON" ]; then
    echo "pre-commit: no Python interpreter found on PATH (tried python3, python, py)." >&2
    echo "pre-commit: install Python, then: pip install -r scripts/requirements-test.txt" >&2
    echo "pre-commit: or bypass with git commit --no-verify (not recommended)." >&2
    exit 1
fi

if ! "$PYTHON" -m pytest --version >/dev/null 2>&1; then
    echo "pre-commit: pytest is not installed. Run: pip install -r scripts/requirements-test.txt" >&2
    echo "pre-commit: or bypass this check with git commit --no-verify (not recommended)." >&2
    exit 1
fi

echo "pre-commit: running scripts/tests (structure + secret-hygiene checks)..."
if ! "$PYTHON" -m pytest scripts/tests -q; then
    echo "" >&2
    echo "pre-commit: BLOCKED -- scripts/tests failed. Fix the finding, or if it's a" >&2
    echo "confirmed false positive, add its exact value to docs/secrets-scan-allowlist.txt." >&2
    echo "Bypass with git commit --no-verify only if you are certain." >&2
    exit 1
fi

echo "pre-commit: OK"
"""


def pre_commit_hook() -> str:
    return _PRE_COMMIT_HOOK


def sops_yaml_scaffold() -> str:
    return _SOPS_YAML


def readme(*, timestamp: str, context: str, stats: dict) -> str:
    return f"""\
# homelab

Kubernetes disaster-recovery backup and Flux-GitOps-ready source tree,
generated by `scripts/backup.py` from a live cluster. It is not yet wired
up to Flux: nothing in this repo has been applied to any cluster.

## What this is

Two things at once, by design:

1. **Disaster-recovery backup.** `kubernetes/apps/*/*/app/values.yaml`,
   `kubernetes/raw/`, and `kubernetes/cluster/` hold enough of the current
   cluster's declared state to rebuild the workloads on a fresh cluster.
2. **Flux migration scaffold.** Every `HelmRelease`, `HelmRepository`/
   `OCIRepository`, and Flux `Kustomization` CR under `kubernetes/` is
   pre-generated. Installing Flux and pointing it at this repo (via a
   `GitRepository` named `flux-system` and the root Kustomization at
   `kubernetes/flux/config/cluster.yaml`) is most of what's left to do.

## Last capture

- Captured: {timestamp}
- Kube context: `{context}`
- Helm releases: {stats.get('release_count', 0)}
- Helm repositories: {stats.get('repo_count', 0)}
- Cluster-scoped resources: {stats.get('cluster_resource_count', 0)}
- Cluster-scoped resources kept local-only, not committed: {stats.get('cluster_local_only_count', 0)}
- Raw namespaced resources: {stats.get('raw_resource_count', 0)}
- Secrets inventoried (metadata only): {stats.get('secret_count', 0)}

See `docs/inventory.md` for the full human-readable snapshot.

## kubernetes/.local/ (gitignored, not committed)

Built-in Kubernetes objects (RBAC created by kube-apiserver/kubeadm at
bootstrap, resources owned by the Tigera/Calico operator, dynamically
provisioned PersistentVolumes, built-in PriorityClasses) still get backed
up -- just under `kubernetes/.local/cluster/<kind>/`, which `.gitignore`
excludes. Committing these means git thinks it owns content that a
Kubernetes version upgrade or a PVC recreate changes out from under you,
with no actual disaster-recovery value (they're recreated automatically).
See `skipfilter.classify_cluster_locality` in `scripts/k8s_backup/skipfilter.py`
for the exact rules.

`kubernetes/.local/variable-substitutions.yaml` (also gitignored) is where
you list exact literal values -- an internal hostname, an account email --
that should be replaced with a `${{PLACEHOLDER}}` in every git-tracked
captured file. It's scaffolded with a commented-out example on first run;
uncomment and edit it, then re-run `capture`. A file carrying a placeholder
is not directly `kubectl apply`-able until you substitute the real value
back in (by hand, or with `envsubst`).

## How to re-run

```
python scripts/backup.py all --output . --context <kube-context>
```

Re-running is idempotent: it updates files in place, adds new ones for
resources that appeared since the last run, and removes files for
resources that were deleted from the cluster (a summary is printed at the
end). Use `--dry-run` to preview without writing anything, `--verbose` for
per-resource logging, and the `capture` / `generate` subcommands to run
just the cluster-reading half or just the local YAML-synthesis half.

## Out of scope (explicitly, so no one gets a false sense of security)

- **PersistentVolume data is not backed up here.** This repo captures the
  Kubernetes objects that describe storage (PVCs, PVs, StorageClasses),
  not the bytes on the Synology NFS backing them. Use Synology snapshots,
  Velero, or a per-application backup tool for actual data.
- **etcd is not backed up here.** Cluster state (not workload data) lives
  in etcd on the control-plane nodes; back that up separately if you need
  full control-plane disaster recovery.
- **Secret values are never captured.** `docs/secrets-inventory.csv` has
  metadata only (namespace, name, type, key names, creation time). See
  `docs/sops-planning.md` for the per-secret disposition checklist.
- **IP addresses found in captured manifests are inventoried, not
  redacted.** `docs/ip-inventory.csv` lists every address, which file it's
  in, and a best-effort guess at what it's for (a node, the MetalLB pool,
  the NFS server, ...). Private/RFC1918 addresses are expected in a
  homelab backup; a public address is flagged as a real finding by
  `scripts/tests`.
- **No age key is generated.** `.sops.yaml` is a scaffold with a
  placeholder recipient; replace it with a real key before encrypting
  anything.
- **Inter-app `dependsOn` relationships are not inferred.** Every `ks.yaml`
  has an empty `spec.dependsOn` with a comment; fill those in by hand.
- **Flux is not installed and nothing here has been applied.** This script
  is read-only against the cluster and write-only against this directory.

## Testing

```
pip install -r scripts/requirements-test.txt
git config core.hooksPath .githooks
pytest scripts/tests
```

`git config core.hooksPath .githooks` (this script sets it automatically
whenever it finds an existing `.git` here) activates `.githooks/pre-commit`,
which runs this whole suite before every `git commit` and blocks the commit
on failure -- this is what stops a credential from reaching git history in
the first place, rather than only being caught after the fact. Bypass with
`git commit --no-verify` if you're certain a failure is safe to ignore.

Two kinds of checks, both real tests (not linters): `test_structure.py`
verifies the tree matches what the generator promises (every release has
its `ks.yaml`/`helmrelease.yaml`/values files, every kustomization lists
exactly what's on disk, no filename uses a character Windows rejects), and
`test_secrets_hygiene.py` scans the whole repo for credential material --
private key headers, AWS/GitHub/Slack tokens, JWTs, any captured `kind:
Secret`, plaintext values behind password/token/secret-looking keys in
`values.yaml`, and high-entropy strings anywhere in a captured manifest.
That last category exists because this generator never writes a Secret's
data to disk, but a *different* resource kind (a Deployment, say) can still
carry a credential baked into it by whatever chart created it -- e.g. a
token passed as a container command-line argument instead of a Secret env
var. A failure means a human needs to look at it: either fix/rotate the
credential, or if it's a confirmed false positive, add its exact value to
`docs/secrets-scan-allowlist.txt` (never weaken the check itself for that).

## Verification

```
kubeconform -summary -verbose \\
  -skip HelmRelease,Kustomization,IPAddressPool,L2Advertisement,ClusterIssuer,Certificate,Issuer,Cluster,Pooler,Backup,ScheduledBackup \\
  -ignore-filename-pattern '.*values(-all)?\\.yaml$' \\
  -ignore-filename-pattern '.*release\\.yaml$' \\
  kubernetes/apps kubernetes/cluster kubernetes/raw
```

The two `-ignore-filename-pattern` flags skip `values.yaml`/`values-all.yaml`
(Helm values, not Kubernetes manifests) and `release.yaml` (this script's
own backup-identity record, also not a manifest) -- without them,
kubeconform correctly reports them as errors ("missing 'kind' key") since
they were never meant to be Kubernetes objects. The `-skip` list covers
CRD kinds kubeconform has no offline schema for; that's expected, not a
bug.

## Next steps toward Flux

1. Review every `kubernetes/apps/*/*/release.yaml` with
   `chartSource.resolved: false` -- Helm doesn't record which configured
   repo a chart came from, so a few releases may need their
   `helmrelease.yaml` `sourceRef` filled in by hand (see the warning
   comment in each affected file).
2. Curate `kubernetes/raw/` into proper `kubernetes/apps/<namespace>/<app>/`
   directories where it makes sense.
3. Fill in `spec.dependsOn` on the `ks.yaml` files that need a startup
   order (e.g. anything depending on CloudNativePG or Authentik).
4. Generate a real age key and update `.sops.yaml`, then start moving
   secrets into SOPS-encrypted files per `docs/sops-planning.md`.
5. Install Flux, create a `GitRepository` named `flux-system` pointing at
   this repo, and apply `kubernetes/flux/config/cluster.yaml`.
"""
