apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: semaphore-cluster-health
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: semaphore-cluster-health
subjects:
- kind: ServiceAccount
  name: semaphore
  namespace: cluster-access
