apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    storage.k8s.io/name: nfs
  name: babybuddy-config
  namespace: babybuddy
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
