apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: semaphore
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: cluster-access
      homelab.local/category: system
      homelab.local/env: prod
      homelab.local/managed-by: hand
  interval: 30m
  path: ./kubernetes/prod/system/cluster-access/semaphore/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cluster-access
  dependsOn: []
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
      optional: true
    - kind: Secret
      name: cluster-secrets
      optional: true
