apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: traefik_redirect-https@kubernetescrd
  name: homeassistant
  namespace: homeassistant
spec:
  ingressClassName: traefik
  rules:
  - host: homeassistant.${BASE_DOMAIN}
    http:
      paths:
      - backend:
          service:
            name: homeassistant
            port:
              number: 8123
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - homeassistant.${BASE_DOMAIN}
    secretName: homeassistant-http-tls
