apiVersion: v1
kind: Namespace
metadata:
  labels:
    homelab.local/category: services
    homelab.local/data: stateless
    homelab.local/exposure: lan
    homelab.local/login: authentik-oidc
  name: homepage
