apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-retain-rwo
  resources:
    requests:
      storage: 1Gi
