apiVersion: v1
kind: Secret
metadata:
  name: authentik-organizr-oidc
  namespace: authentik
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
data:
  client-secret: ${AUTHENTIK_ORGANIZR_OIDC_CLIENT_SECRET}
