apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: local-path-storage
      homelab.local/category: system
      homelab.local/env: prod
      homelab.local/managed-by: hand
  interval: 30m
  path: ./kubernetes/prod/system/local-path-storage/local-path-provisioner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: local-path-storage
  dependsOn: []
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
      optional: true
    - kind: Secret
      name: cluster-secrets
      optional: true
