"""Structural checks: the generated tree matches the layout the generator
promises (task spec's "Target output structure"), and every generated file
is internally consistent with the others (e.g. a namespace's kustomization
actually lists every release dir that exists on disk).

These are regression tests for the generator, not just the output: a bug
that makes capture.py and generate.py disagree about a path shows up here
even if kubeconform would happily validate each file in isolation.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from k8s_backup.ownership import handwritten_protected_paths, is_handwritten, is_promoted

REQUIRED_TOP_FILES = ["README.md", ".gitignore", ".gitattributes", ".sops.yaml"]
REQUIRED_TOP_DIRS = ["docs", "kubernetes", "scripts", ".github"]
REQUIRED_DOCS = ["inventory.md", "secrets-inventory.csv", "sops-planning.md", "redactions.md", "ip-inventory.csv"]
# Gitignored or empty, so a fresh clone doesn't have them until a run creates them.
LOCAL_ONLY_TOP_DIRS = {"docs", ".github"}

GENERATED_HEADER_PREFIX = "# Generated by k8s-backup-repo-gen on "


def _skip_without_local_capture(repo_root: Path, what: str) -> None:
    """docs/ and kubernetes/raw/ are written by capture and gitignored, so a
    fresh clone (e.g. a cloud session) has neither. kubernetes/.local/ is
    capture's other gitignored output, so its absence means capture never
    ran in this checkout.
    """
    if not (repo_root / "kubernetes" / ".local").is_dir():
        pytest.skip(f"{what} isn't tracked in git, so a fresh clone doesn't have it")


def _awaiting_capture(release_dir: Path) -> bool:
    """Just marked .promote, not captured/generated yet: nothing to check
    until the next run (test_promoted_releases_have_been_captured says so).
    """
    return is_promoted(release_dir) and not (release_dir / "ks.yaml").exists()


def _release_dirs(repo_root: Path):
    apps = repo_root / "kubernetes" / "apps"
    if not apps.exists():
        return
    for ns_dir in sorted(p for p in apps.iterdir() if p.is_dir()):
        for release_dir in sorted(p for p in ns_dir.iterdir() if p.is_dir()):
            if not _awaiting_capture(release_dir):
                yield ns_dir.name, release_dir.name, release_dir


def test_promoted_releases_have_been_captured(repo_root):
    apps = repo_root / "kubernetes" / "apps"
    pending = sorted(
        d.relative_to(repo_root).as_posix()
        for d in (apps.glob("*/*") if apps.exists() else [])
        if d.is_dir() and _awaiting_capture(d)
    )
    assert not pending, (
        f"marked .promote but not captured yet: {pending} -- run "
        "`python scripts/backup.py all --output .` before committing"
    )


def _namespace_dirs(repo_root: Path):
    apps = repo_root / "kubernetes" / "apps"
    if not apps.exists():
        return
    for ns_dir in sorted(p for p in apps.iterdir() if p.is_dir()):
        yield ns_dir.name, ns_dir


@pytest.mark.parametrize("name", REQUIRED_TOP_FILES)
def test_top_level_file_exists(repo_root, name):
    assert (repo_root / name).is_file(), f"missing required top-level file: {name}"


@pytest.mark.parametrize("name", REQUIRED_TOP_DIRS)
def test_top_level_dir_exists(repo_root, name):
    if name in LOCAL_ONLY_TOP_DIRS:
        _skip_without_local_capture(repo_root, f"{name}/")
    assert (repo_root / name).is_dir(), f"missing required top-level directory: {name}"


@pytest.mark.parametrize("name", REQUIRED_DOCS)
def test_docs_file_exists(repo_root, name):
    _skip_without_local_capture(repo_root, f"docs/{name}")
    assert (repo_root / "docs" / name).is_file(), f"missing docs/{name}"


def _assert_wires_substitutions(doc) -> None:
    """Both refs, always, and optional so Flux doesn't hard-fail before the
    ConfigMap/Secret exists on the cluster. Never conditional on the local
    substitutions file: a clone without it must generate the same thing.
    """
    substitute_from = doc["spec"].get("postBuild", {}).get("substituteFrom", [])
    assert [(entry["kind"], entry["name"]) for entry in substitute_from] == [
        ("ConfigMap", "cluster-settings"),
        ("Secret", "cluster-secrets"),
    ]
    for entry in substitute_from:
        assert entry.get("optional") is True, "substituteFrom entries must be optional so Flux doesn't hard-fail before the ConfigMap/Secret exists on the cluster"


def test_flux_root_kustomization_exists(repo_root, load_yaml):
    path = repo_root / "kubernetes" / "flux" / "config" / "cluster.yaml"
    assert path.is_file()
    doc = load_yaml(path)
    assert doc["apiVersion"] == "kustomize.toolkit.fluxcd.io/v1"
    assert doc["kind"] == "Kustomization"
    assert doc["spec"]["path"] == "./kubernetes/apps"
    _assert_wires_substitutions(doc)


def test_repositories_kustomization_lists_every_repo_file(repo_root, load_yaml):
    repo_dir = repo_root / "kubernetes" / "flux" / "meta" / "repositories"
    assert repo_dir.is_dir()
    kustomization = load_yaml(repo_dir / "kustomization.yaml")
    on_disk = {p.name for p in repo_dir.glob("*.yaml") if p.name != "kustomization.yaml"}
    assert set(kustomization["resources"]) == on_disk


def test_every_repository_cr_is_helmrepo_or_ocirepo(repo_root, load_yaml):
    repo_dir = repo_root / "kubernetes" / "flux" / "meta" / "repositories"
    for path in repo_dir.glob("*.yaml"):
        if path.name == "kustomization.yaml":
            continue
        doc = load_yaml(path)
        # GitRepository: a chart that's only published in a git repo (e.g.
        # local-path-provisioner), referenced by a hand-written HelmRelease.
        assert doc["kind"] in ("HelmRepository", "OCIRepository", "GitRepository"), path
        assert doc["apiVersion"] == "source.toolkit.fluxcd.io/v1", path
        assert doc["metadata"]["namespace"] == "flux-system", path


def test_cluster_kustomization_lists_every_captured_resource(repo_root, load_yaml):
    cluster_dir = repo_root / "kubernetes" / "cluster"
    assert cluster_dir.is_dir()
    kustomization = load_yaml(cluster_dir / "kustomization.yaml")
    on_disk = {
        f"{kind_dir.name}/{f.name}"
        for kind_dir in cluster_dir.iterdir()
        if kind_dir.is_dir()
        for f in kind_dir.glob("*.yaml")
    }
    assert set(kustomization["resources"]) == on_disk


def test_raw_readme_exists(repo_root):
    _skip_without_local_capture(repo_root, "kubernetes/raw/README.md")
    assert (repo_root / "kubernetes" / "raw" / "README.md").is_file()


def test_cluster_resources_kustomization_wires_substitutions(repo_root, load_yaml):
    ks_path = repo_root / "kubernetes" / "flux" / "config" / "cluster-resources.yaml"
    if not ks_path.exists():
        pytest.skip("no kubernetes/cluster yet; run `capture` and `generate` first")

    doc = load_yaml(ks_path)
    assert doc["apiVersion"] == "kustomize.toolkit.fluxcd.io/v1"
    assert doc["kind"] == "Kustomization"
    assert doc["metadata"]["name"] == "cluster-resources"
    assert doc["spec"]["path"] == "./kubernetes/cluster"
    assert doc["spec"]["prune"] is True
    _assert_wires_substitutions(doc)


def test_local_only_tree_is_gitignored(repo_root):
    gitignore = (repo_root / ".gitignore").read_text(encoding="utf-8")
    assert "kubernetes/.local/" in gitignore, (
        ".gitignore must exclude kubernetes/.local/ -- built-in/system resources and the "
        "real variable-substitutions.yaml are backed up there but must never be committed"
    )


def test_local_only_cluster_resources_absent_from_tracked_tree(repo_root, load_yaml):
    """Anything skipfilter.classify_cluster_locality would route to
    kubernetes/.local/ must not also exist in the git-tracked
    kubernetes/cluster/ tree (that would defeat the point of the split).
    Uses the real classifier rather than reimplementing its rules, so this
    can't silently drift out of sync with skipfilter.py.
    """
    from k8s_backup.skipfilter import classify_cluster_locality

    cluster_dir = repo_root / "kubernetes" / "cluster"
    if not cluster_dir.exists():
        pytest.skip("no kubernetes/cluster yet; run `capture` first")

    offenders = []
    for kind_dir in cluster_dir.iterdir():
        if not kind_dir.is_dir():
            continue
        for f in kind_dir.glob("*.yaml"):
            try:
                doc = load_yaml(f)
            except Exception:
                continue
            if doc and classify_cluster_locality(kind_dir.name, doc):
                offenders.append(f.relative_to(repo_root))
    assert not offenders, f"built-in/dynamic/infra resource(s) leaked into the git-tracked tree: {offenders}"


def test_ip_inventory_csv_has_expected_columns(repo_root):
    import csv

    _skip_without_local_capture(repo_root, "docs/ip-inventory.csv")
    path = repo_root / "docs" / "ip-inventory.csv"
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        assert reader.fieldnames == ["ip", "classification", "purpose", "file", "occurrences", "field_paths"]


def test_pre_commit_hook_exists_and_looks_runnable(repo_root):
    path = repo_root / ".githooks" / "pre-commit"
    assert path.is_file(), ".githooks/pre-commit is missing"
    text = path.read_text(encoding="utf-8")
    assert text.startswith("#!/bin/sh"), ".githooks/pre-commit must start with a shebang"
    assert "pytest scripts/tests" in text


def test_namespace_dirs_have_required_files(repo_root):
    for ns_name, ns_dir in _namespace_dirs(repo_root):
        assert (ns_dir / "namespace.yaml").is_file(), f"{ns_name}/namespace.yaml missing"
        assert (ns_dir / "kustomization.yaml").is_file(), f"{ns_name}/kustomization.yaml missing"


def test_namespace_kustomization_lists_namespace_and_every_release(repo_root, load_yaml):
    for ns_name, ns_dir in _namespace_dirs(repo_root):
        kustomization = load_yaml(ns_dir / "kustomization.yaml")
        resources = set(kustomization["resources"])
        assert "namespace.yaml" in resources, ns_name
        release_dirs = {p.name for p in ns_dir.iterdir() if p.is_dir() and not _awaiting_capture(p)}
        expected = {f"{r}/ks.yaml" for r in release_dirs}
        assert resources - {"namespace.yaml"} == expected, ns_name


RELEASE_REQUIRED_FILES = [
    "release.yaml",
    "ks.yaml",
    "app/kustomization.yaml",
    "app/helmrelease.yaml",
    "app/values.yaml",
    "app/values-all.yaml",
]
# Written by capture; a hand-written release (.handwritten marker) has none.
CAPTURED_RELEASE_FILES = {"release.yaml", "app/values.yaml", "app/values-all.yaml"}
# A promoted release (.promote marker) is plain manifests, not a Helm release.
PROMOTED_RELEASE_FILES = {"ks.yaml", "app/kustomization.yaml"}


@pytest.mark.parametrize("rel_file", RELEASE_REQUIRED_FILES)
def test_every_release_has_required_files(repo_root, rel_file):
    found_any = False
    for ns_name, release_name, release_dir in _release_dirs(repo_root):
        found_any = True
        if is_promoted(release_dir):
            present = (release_dir / rel_file).exists()
            assert present == (rel_file in PROMOTED_RELEASE_FILES), (
                f"{ns_name}/{release_name}/{rel_file}: a promoted release has exactly "
                f"{sorted(PROMOTED_RELEASE_FILES)} of these"
            )
            continue
        if is_handwritten(release_dir):
            if rel_file in CAPTURED_RELEASE_FILES:
                assert not (release_dir / rel_file).exists(), (
                    f"{ns_name}/{release_name}/{rel_file}: hand-written releases must not carry "
                    "captured files -- generate would treat the folder as captured"
                )
                continue
            if rel_file == "app/helmrelease.yaml":
                continue  # a hand-written release may be plain manifests
        assert (release_dir / rel_file).is_file(), f"{ns_name}/{release_name}/{rel_file} missing"
    if not found_any:
        pytest.skip("no releases captured")


def test_ks_yaml_matches_its_release(repo_root, load_yaml):
    kustomizations = {release_name for _, release_name, _ in _release_dirs(repo_root)}
    for ns_name, release_name, release_dir in _release_dirs(repo_root):
        doc = load_yaml(release_dir / "ks.yaml")
        assert doc["apiVersion"] == "kustomize.toolkit.fluxcd.io/v1"
        assert doc["kind"] == "Kustomization"
        assert doc["metadata"]["name"] == release_name
        assert doc["metadata"]["namespace"] == "flux-system"
        assert doc["spec"]["targetNamespace"] == ns_name
        assert doc["spec"]["path"] == f"./kubernetes/apps/{ns_name}/{release_name}/app"
        # A dependency on a Kustomization that doesn't exist never becomes Ready.
        for dep in doc["spec"]["dependsOn"]:
            assert dep["name"] in kustomizations and dep["name"] != release_name, (
                f"{ns_name}/{release_name}/ks.yaml: dependsOn {dep['name']!r} isn't another "
                "Kustomization under kubernetes/apps/"
            )
        assert doc["spec"]["prune"] is True


def test_helmrelease_matches_its_release(repo_root, load_yaml):
    for ns_name, release_name, release_dir in _release_dirs(repo_root):
        if is_handwritten(release_dir) or is_promoted(release_dir):
            continue  # no release.yaml to match
        release_meta = load_yaml(release_dir / "release.yaml")
        hr = load_yaml(release_dir / "app" / "helmrelease.yaml")
        assert hr["apiVersion"] == "helm.toolkit.fluxcd.io/v2"
        assert hr["kind"] == "HelmRelease"
        assert hr["metadata"]["name"] == release_name
        assert hr["metadata"]["namespace"] == ns_name
        assert hr["spec"]["chart"]["spec"]["chart"] == release_meta["chart"]
        assert hr["spec"]["chart"]["spec"]["version"] == release_meta["chartVersion"]

        source_ref = hr["spec"]["chart"]["spec"]["sourceRef"]
        chart_source = release_meta.get("chartSource") or {}
        if chart_source.get("resolved"):
            assert source_ref["name"] == chart_source["name"], (
                f"{ns_name}/{release_name}: helmrelease.yaml sourceRef doesn't match "
                "release.yaml's resolved chartSource"
            )
            assert source_ref["kind"] == chart_source["kind"]
        else:
            assert source_ref["name"] == "REPLACE-ME", (
                f"{ns_name}/{release_name}: chartSource is unresolved in release.yaml but "
                "helmrelease.yaml doesn't carry the REPLACE-ME placeholder -- did someone "
                "hand-edit one of these without the other?"
            )


def test_handwritten_helmrelease_is_consistent(repo_root, load_yaml):
    repo_dir = repo_root / "kubernetes" / "flux" / "meta" / "repositories"
    repo_names = {
        load_yaml(p)["metadata"]["name"] for p in repo_dir.glob("*.yaml") if p.name != "kustomization.yaml"
    }
    for ns_name, release_name, release_dir in _release_dirs(repo_root):
        hr_path = release_dir / "app" / "helmrelease.yaml"
        if not is_handwritten(release_dir) or not hr_path.is_file():
            continue  # plain manifests have no HelmRelease to check
        hr = load_yaml(hr_path)
        assert hr["apiVersion"] == "helm.toolkit.fluxcd.io/v2"
        assert hr["kind"] == "HelmRelease"
        assert hr["metadata"]["name"] == release_name
        source_ref = hr["spec"]["chart"]["spec"]["sourceRef"]
        assert source_ref["name"] in repo_names, (
            f"{ns_name}/{release_name}: sourceRef {source_ref['name']!r} has no file in "
            "kubernetes/flux/meta/repositories/"
        )


def test_app_kustomization_lists_helmrelease(repo_root, load_yaml):
    for ns_name, release_name, release_dir in _release_dirs(repo_root):
        if is_promoted(release_dir):
            continue  # see test_promoted_release_is_consistent
        doc = load_yaml(release_dir / "app" / "kustomization.yaml")
        if is_handwritten(release_dir) and not (release_dir / "app" / "helmrelease.yaml").is_file():
            # Plain manifests: whatever is in app/ must be listed.
            on_disk = sorted(q.name for q in (release_dir / "app").glob("*.yaml") if q.name != "kustomization.yaml")
            assert sorted(doc["resources"]) == on_disk, f"{ns_name}/{release_name}"
            continue
        assert "helmrelease.yaml" in doc["resources"], f"{ns_name}/{release_name}"
        assert "values.yaml" not in doc["resources"], (
            f"{ns_name}/{release_name}: values.yaml is a Helm values file, not a manifest -- "
            "it must never appear in a Kustomize resources: list"
        )


def test_promoted_release_is_consistent(repo_root, load_yaml):
    from k8s_backup.secretscan import REDACTION_PLACEHOLDER

    for ns_name, release_name, release_dir in _release_dirs(repo_root):
        if not is_promoted(release_dir):
            continue
        app_dir = release_dir / "app"
        manifests = {p.name for p in app_dir.glob("*.yaml") if p.name != "kustomization.yaml"}
        assert set(load_yaml(app_dir / "kustomization.yaml")["resources"]) == manifests, (
            f"{ns_name}/{release_name}: app/kustomization.yaml doesn't list exactly the manifests in app/"
        )
        for name in manifests:
            text = (app_dir / name).read_text(encoding="utf-8")
            assert REDACTION_PLACEHOLDER not in text, (
                f"{ns_name}/{release_name}/app/{name}: Flux would apply the redaction placeholder"
            )
            doc = load_yaml(app_dir / name)
            assert doc["metadata"].get("namespace") in (None, ns_name), f"{ns_name}/{release_name}/app/{name}"


GENERATED_YAML_GLOBS = [
    "kubernetes/apps/*/*/ks.yaml",
    "kubernetes/apps/*/*/app/helmrelease.yaml",
    "kubernetes/apps/*/*/app/kustomization.yaml",
    "kubernetes/apps/*/kustomization.yaml",
    "kubernetes/flux/config/cluster.yaml",
    "kubernetes/flux/meta/repositories/*.yaml",
    "kubernetes/cluster/kustomization.yaml",
]


def test_generated_files_carry_the_generated_header(repo_root):
    handwritten = handwritten_protected_paths(repo_root)
    checked = 0
    for pattern in GENERATED_YAML_GLOBS:
        for path in repo_root.glob(pattern):
            if path.name == "kustomization.yaml" and "repositories" in path.parts:
                continue
            if path.relative_to(repo_root).as_posix() in handwritten:
                continue
            checked += 1
            first_line = path.read_text(encoding="utf-8").splitlines()[0]
            assert first_line.startswith(GENERATED_HEADER_PREFIX), path
    assert checked > 0, "no generated files found -- run `capture` and `generate` first"


UNSAFE_FILENAME_CHARS = set('<>:"/\\|?*')


def test_no_windows_unsafe_filenames(all_files, repo_root):
    for path in all_files:
        if path.name == ".git":
            continue
        bad = UNSAFE_FILENAME_CHARS & set(path.name)
        assert not bad, f"{path.relative_to(repo_root)} contains characters unsafe on Windows: {bad}"


def test_no_namespace_is_defined_twice(repo_root):
    # Applied by both `cluster` (apps/) and `cluster-resources` (cluster/),
    # the two Flux Kustomizations would keep relabelling it.
    apps = repo_root / "kubernetes" / "apps"
    cluster_ns = repo_root / "kubernetes" / "cluster" / "namespace"
    if not apps.is_dir() or not cluster_ns.is_dir():
        return  # nothing under kubernetes/cluster/namespace/, so nothing twice
    both = sorted(p.stem for p in cluster_ns.glob("*.yaml") if (apps / p.stem / "namespace.yaml").is_file())
    assert not both, f"namespaces in both apps/<ns>/namespace.yaml and cluster/namespace/: {both}"


_VARIABLE_RE = re.compile(r"(?<!\$)\$\{([A-Za-z_][A-Za-z0-9_]*)\}")


def test_every_substituted_variable_is_defined(repo_root, load_yaml):
    """Flux substitutes an undefined ${VAR} as an empty string (or fails the
    apply in strict mode), so every one used under kubernetes/ must be a key
    of cluster-settings (public, in git) or a field of the cluster-secrets
    ExternalSecret (private, from Vaultwarden). The test overlay's own
    variables come from cluster-substitutions-test.
    """
    settings = load_yaml(repo_root / "kubernetes/flux/meta/vars/cluster-settings.yaml")["data"]
    test_vars = load_yaml(repo_root / "kubernetes/flux/meta/vars/cluster-substitutions-test.yaml")["data"]
    external = load_yaml(repo_root / "kubernetes/secrets/cluster-secrets.yaml")
    secrets = {d["secretKey"] for d in external["spec"]["data"]}
    assert not set(settings) & secrets, "a variable is defined both in git and in Vaultwarden"
    for d in external["spec"]["data"]:
        assert d["remoteRef"]["property"] == d["secretKey"], f"{d['secretKey']}: field name must match the variable"

    kubernetes = repo_root / "kubernetes"
    local_root = kubernetes / ".local"
    used: dict[str, set[str]] = {}
    for path in kubernetes.rglob("*.yaml"):
        if path.is_relative_to(local_root) or path.parts[-3:-1] == ("flux", "config") and path.name == "gotk-components.yaml":
            continue
        for name in _VARIABLE_RE.findall(path.read_text(encoding="utf-8")):
            used.setdefault(name, set()).add(path.relative_to(repo_root).as_posix())
    defined = set(settings) | secrets | set(test_vars)
    undefined = {name: sorted(paths)[:3] for name, paths in used.items() if name not in defined}
    assert not undefined, f"variables used but defined nowhere: {undefined}"
