"""Structural checks: the generated tree matches the layout the generator
promises (task spec's "Target output structure"), and every generated file
is internally consistent with the others (e.g. a namespace's kustomization
actually lists every release dir that exists on disk).

These are regression tests for the generator, not just the output: a bug
that makes capture.py and generate.py disagree about a path shows up here
even if kubeconform would happily validate each file in isolation.
"""

from __future__ import annotations

from pathlib import Path

import pytest

REQUIRED_TOP_FILES = ["README.md", ".gitignore", ".gitattributes", ".sops.yaml"]
REQUIRED_TOP_DIRS = ["docs", "kubernetes", "scripts", ".github"]
REQUIRED_DOCS = ["inventory.md", "secrets-inventory.csv", "sops-planning.md", "redactions.md", "ip-inventory.csv"]

GENERATED_HEADER_PREFIX = "# Generated by k8s-backup-repo-gen on "


def _release_dirs(repo_root: Path):
    apps = repo_root / "kubernetes" / "apps"
    if not apps.exists():
        return
    for ns_dir in sorted(p for p in apps.iterdir() if p.is_dir()):
        for release_dir in sorted(p for p in ns_dir.iterdir() if p.is_dir()):
            yield ns_dir.name, release_dir.name, release_dir


def _namespace_dirs(repo_root: Path):
    apps = repo_root / "kubernetes" / "apps"
    if not apps.exists():
        return
    for ns_dir in sorted(p for p in apps.iterdir() if p.is_dir()):
        yield ns_dir.name, ns_dir


@pytest.mark.parametrize("name", REQUIRED_TOP_FILES)
def test_top_level_file_exists(repo_root, name):
    assert (repo_root / name).is_file(), f"missing required top-level file: {name}"


@pytest.mark.parametrize("name", REQUIRED_TOP_DIRS)
def test_top_level_dir_exists(repo_root, name):
    assert (repo_root / name).is_dir(), f"missing required top-level directory: {name}"


@pytest.mark.parametrize("name", REQUIRED_DOCS)
def test_docs_file_exists(repo_root, name):
    assert (repo_root / "docs" / name).is_file(), f"missing docs/{name}"


def test_flux_root_kustomization_exists(repo_root, load_yaml):
    path = repo_root / "kubernetes" / "flux" / "config" / "cluster.yaml"
    assert path.is_file()
    doc = load_yaml(path)
    assert doc["apiVersion"] == "kustomize.toolkit.fluxcd.io/v1"
    assert doc["kind"] == "Kustomization"
    assert doc["spec"]["path"] == "./kubernetes/apps"


def test_repositories_kustomization_lists_every_repo_file(repo_root, load_yaml):
    repo_dir = repo_root / "kubernetes" / "flux" / "meta" / "repositories"
    assert repo_dir.is_dir()
    kustomization = load_yaml(repo_dir / "kustomization.yaml")
    on_disk = {p.name for p in repo_dir.glob("*.yaml") if p.name != "kustomization.yaml"}
    assert set(kustomization["resources"]) == on_disk


def test_every_repository_cr_is_helmrepo_or_ocirepo(repo_root, load_yaml):
    repo_dir = repo_root / "kubernetes" / "flux" / "meta" / "repositories"
    for path in repo_dir.glob("*.yaml"):
        if path.name == "kustomization.yaml":
            continue
        doc = load_yaml(path)
        assert doc["kind"] in ("HelmRepository", "OCIRepository"), path
        assert doc["apiVersion"] == "source.toolkit.fluxcd.io/v1", path
        assert doc["metadata"]["namespace"] == "flux-system", path


def test_cluster_kustomization_lists_every_captured_resource(repo_root, load_yaml):
    cluster_dir = repo_root / "kubernetes" / "cluster"
    assert cluster_dir.is_dir()
    kustomization = load_yaml(cluster_dir / "kustomization.yaml")
    on_disk = {
        f"{kind_dir.name}/{f.name}"
        for kind_dir in cluster_dir.iterdir()
        if kind_dir.is_dir()
        for f in kind_dir.glob("*.yaml")
    }
    assert set(kustomization["resources"]) == on_disk


def test_raw_readme_exists(repo_root):
    assert (repo_root / "kubernetes" / "raw" / "README.md").is_file()


def test_local_substitution_manifests_are_well_formed(repo_root, load_yaml):
    from k8s_backup.varsub import LOCAL_CONFIGMAP_PATH, LOCAL_SECRET_PATH, load_substitutions

    substitutions = load_substitutions(repo_root)
    configmap_path = repo_root.joinpath(*LOCAL_CONFIGMAP_PATH)
    secret_path = repo_root.joinpath(*LOCAL_SECRET_PATH)

    has_configmap_vars = any(s.get("sensitivity", "configmap") != "secret" for s in substitutions)
    has_secret_vars = any(s.get("sensitivity") == "secret" for s in substitutions)

    if has_configmap_vars:
        doc = load_yaml(configmap_path)
        assert doc["kind"] == "ConfigMap"
        assert doc["metadata"]["name"] == "cluster-substitutions"
        assert doc["metadata"]["namespace"] == "flux-system"
    if has_secret_vars:
        doc = load_yaml(secret_path)
        assert doc["kind"] == "Secret"
        assert doc["metadata"]["name"] == "cluster-substitutions-secret"
        assert doc["metadata"]["namespace"] == "flux-system"


def test_cluster_resources_kustomization_matches_substitutions(repo_root, load_yaml):
    ks_path = repo_root / "kubernetes" / "flux" / "config" / "cluster-resources.yaml"
    if not ks_path.exists():
        pytest.skip("no kubernetes/cluster yet; run `capture` and `generate` first")

    from k8s_backup.varsub import load_substitutions

    substitutions = load_substitutions(repo_root)
    has_configmap_vars = any(s.get("sensitivity", "configmap") != "secret" for s in substitutions)
    has_secret_vars = any(s.get("sensitivity") == "secret" for s in substitutions)

    doc = load_yaml(ks_path)
    assert doc["apiVersion"] == "kustomize.toolkit.fluxcd.io/v1"
    assert doc["kind"] == "Kustomization"
    assert doc["metadata"]["name"] == "cluster-resources"
    assert doc["spec"]["path"] == "./kubernetes/cluster"
    assert doc["spec"]["prune"] is True

    substitute_from = doc["spec"].get("postBuild", {}).get("substituteFrom", [])
    kinds_present = {entry["kind"] for entry in substitute_from}
    assert ("ConfigMap" in kinds_present) == has_configmap_vars
    assert ("Secret" in kinds_present) == has_secret_vars
    for entry in substitute_from:
        assert entry.get("optional") is True, "substituteFrom entries must be optional so Flux doesn't hard-fail before the ConfigMap/Secret exists on the cluster"


def test_local_only_tree_is_gitignored(repo_root):
    gitignore = (repo_root / ".gitignore").read_text(encoding="utf-8")
    assert "kubernetes/.local/" in gitignore, (
        ".gitignore must exclude kubernetes/.local/ -- built-in/system resources and the "
        "real variable-substitutions.yaml are backed up there but must never be committed"
    )


def test_local_only_cluster_resources_absent_from_tracked_tree(repo_root, load_yaml):
    """Anything skipfilter.classify_cluster_locality would route to
    kubernetes/.local/ must not also exist in the git-tracked
    kubernetes/cluster/ tree (that would defeat the point of the split).
    Uses the real classifier rather than reimplementing its rules, so this
    can't silently drift out of sync with skipfilter.py.
    """
    from k8s_backup.skipfilter import classify_cluster_locality

    cluster_dir = repo_root / "kubernetes" / "cluster"
    if not cluster_dir.exists():
        pytest.skip("no kubernetes/cluster yet; run `capture` first")

    offenders = []
    for kind_dir in cluster_dir.iterdir():
        if not kind_dir.is_dir():
            continue
        for f in kind_dir.glob("*.yaml"):
            try:
                doc = load_yaml(f)
            except Exception:
                continue
            if doc and classify_cluster_locality(kind_dir.name, doc):
                offenders.append(f.relative_to(repo_root))
    assert not offenders, f"built-in/dynamic/infra resource(s) leaked into the git-tracked tree: {offenders}"


def test_ip_inventory_csv_has_expected_columns(repo_root):
    import csv

    path = repo_root / "docs" / "ip-inventory.csv"
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        assert reader.fieldnames == ["ip", "classification", "purpose", "file", "occurrences", "field_paths"]


def test_pre_commit_hook_exists_and_looks_runnable(repo_root):
    path = repo_root / ".githooks" / "pre-commit"
    assert path.is_file(), ".githooks/pre-commit is missing"
    text = path.read_text(encoding="utf-8")
    assert text.startswith("#!/bin/sh"), ".githooks/pre-commit must start with a shebang"
    assert "pytest scripts/tests" in text


def test_namespace_dirs_have_required_files(repo_root):
    for ns_name, ns_dir in _namespace_dirs(repo_root):
        assert (ns_dir / "namespace.yaml").is_file(), f"{ns_name}/namespace.yaml missing"
        assert (ns_dir / "kustomization.yaml").is_file(), f"{ns_name}/kustomization.yaml missing"


def test_namespace_kustomization_lists_namespace_and_every_release(repo_root, load_yaml):
    for ns_name, ns_dir in _namespace_dirs(repo_root):
        kustomization = load_yaml(ns_dir / "kustomization.yaml")
        resources = set(kustomization["resources"])
        assert "namespace.yaml" in resources, ns_name
        release_dirs = {p.name for p in ns_dir.iterdir() if p.is_dir()}
        expected = {f"{r}/ks.yaml" for r in release_dirs}
        assert resources - {"namespace.yaml"} == expected, ns_name


RELEASE_REQUIRED_FILES = [
    "release.yaml",
    "ks.yaml",
    "app/kustomization.yaml",
    "app/helmrelease.yaml",
    "app/values.yaml",
    "app/values-all.yaml",
]


@pytest.mark.parametrize("rel_file", RELEASE_REQUIRED_FILES)
def test_every_release_has_required_files(repo_root, rel_file):
    found_any = False
    for ns_name, release_name, release_dir in _release_dirs(repo_root):
        found_any = True
        assert (release_dir / rel_file).is_file(), f"{ns_name}/{release_name}/{rel_file} missing"
    if not found_any:
        pytest.skip("no releases captured")


def test_ks_yaml_matches_its_release(repo_root, load_yaml):
    for ns_name, release_name, release_dir in _release_dirs(repo_root):
        doc = load_yaml(release_dir / "ks.yaml")
        assert doc["apiVersion"] == "kustomize.toolkit.fluxcd.io/v1"
        assert doc["kind"] == "Kustomization"
        assert doc["metadata"]["name"] == release_name
        assert doc["metadata"]["namespace"] == "flux-system"
        assert doc["spec"]["targetNamespace"] == ns_name
        assert doc["spec"]["path"] == f"./kubernetes/apps/{ns_name}/{release_name}/app"
        assert doc["spec"]["dependsOn"] == []
        assert doc["spec"]["prune"] is True


def test_helmrelease_matches_its_release(repo_root, load_yaml):
    for ns_name, release_name, release_dir in _release_dirs(repo_root):
        release_meta = load_yaml(release_dir / "release.yaml")
        hr = load_yaml(release_dir / "app" / "helmrelease.yaml")
        assert hr["apiVersion"] == "helm.toolkit.fluxcd.io/v2"
        assert hr["kind"] == "HelmRelease"
        assert hr["metadata"]["name"] == release_name
        assert hr["metadata"]["namespace"] == ns_name
        assert hr["spec"]["chart"]["spec"]["chart"] == release_meta["chart"]
        assert hr["spec"]["chart"]["spec"]["version"] == release_meta["chartVersion"]

        source_ref = hr["spec"]["chart"]["spec"]["sourceRef"]
        chart_source = release_meta.get("chartSource") or {}
        if chart_source.get("resolved"):
            assert source_ref["name"] == chart_source["name"], (
                f"{ns_name}/{release_name}: helmrelease.yaml sourceRef doesn't match "
                "release.yaml's resolved chartSource"
            )
            assert source_ref["kind"] == chart_source["kind"]
        else:
            assert source_ref["name"] == "REPLACE-ME", (
                f"{ns_name}/{release_name}: chartSource is unresolved in release.yaml but "
                "helmrelease.yaml doesn't carry the REPLACE-ME placeholder -- did someone "
                "hand-edit one of these without the other?"
            )


def test_app_kustomization_lists_helmrelease(repo_root, load_yaml):
    for ns_name, release_name, release_dir in _release_dirs(repo_root):
        doc = load_yaml(release_dir / "app" / "kustomization.yaml")
        assert "helmrelease.yaml" in doc["resources"], f"{ns_name}/{release_name}"
        assert "values.yaml" not in doc["resources"], (
            f"{ns_name}/{release_name}: values.yaml is a Helm values file, not a manifest -- "
            "it must never appear in a Kustomize resources: list"
        )


GENERATED_YAML_GLOBS = [
    "kubernetes/apps/*/*/ks.yaml",
    "kubernetes/apps/*/*/app/helmrelease.yaml",
    "kubernetes/apps/*/*/app/kustomization.yaml",
    "kubernetes/apps/*/kustomization.yaml",
    "kubernetes/flux/config/cluster.yaml",
    "kubernetes/flux/meta/repositories/*.yaml",
    "kubernetes/cluster/kustomization.yaml",
]


def test_generated_files_carry_the_generated_header(repo_root):
    checked = 0
    for pattern in GENERATED_YAML_GLOBS:
        for path in repo_root.glob(pattern):
            if path.name == "kustomization.yaml" and "repositories" in path.parts:
                continue
            checked += 1
            first_line = path.read_text(encoding="utf-8").splitlines()[0]
            assert first_line.startswith(GENERATED_HEADER_PREFIX), path
    assert checked > 0, "no generated files found -- run `capture` and `generate` first"


UNSAFE_FILENAME_CHARS = set('<>:"/\\|?*')


def test_no_windows_unsafe_filenames(all_files, repo_root):
    for path in all_files:
        if path.name == ".git":
            continue
        bad = UNSAFE_FILENAME_CHARS & set(path.name)
        assert not bad, f"{path.relative_to(repo_root)} contains characters unsafe on Windows: {bad}"
