apiVersion: v1
kind: Secret
metadata:
  name: immich-power-tools-apikey
  namespace: immich
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
data:
  apikey: ${IMMICH_POWER_TOOLS_APIKEY_APIKEY}
  gemini-apikey: ${IMMICH_POWER_TOOLS_APIKEY_GEMINI_APIKEY}
  immich-apikey: ${IMMICH_POWER_TOOLS_APIKEY_IMMICH_APIKEY}
  maps-apikey: ${IMMICH_POWER_TOOLS_APIKEY_MAPS_APIKEY}
