apiVersion: v1
kind: Secret
metadata:
  name: immich-redis-url
  namespace: immich
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
data:
  REDIS_URL: ${IMMICH_REDIS_URL_REDIS_URL}
