apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-superuser
  namespace: immich
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
type: kubernetes.io/basic-auth
data:
  password: ${IMMICH_POSTGRES_SUPERUSER_PASSWORD}
  username: ${IMMICH_POSTGRES_SUPERUSER_USERNAME}
