apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: immich
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
type: kubernetes.io/basic-auth
data:
  password: ${IMMICH_REDIS_PASSWORD_PASSWORD}
