apiVersion: v1
kind: Service
metadata:
  name: immich-power-tools-svc
  namespace: immich
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: immich-power-tools
  sessionAffinity: None
  type: ClusterIP
