apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    homelab.local/category: services
  name: authentik
spec:
  finalizers:
  - kubernetes
