apiVersion: v1
data:
  mosquitto.conf: "listener 1883\nprotocol mqtt\n\nlistener 9001\nprotocol websockets\n\npersistence true\npersistence_location /mosquitto/data/\n\nlog_dest stdout\nlog_type error\nlog_type warning\nlog_type notice\n\nallow_anonymous true\n"
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mqtt
