apiVersion: v1
data:
  mosquitto.conf: |
    listener 1883
    protocol mqtt

    listener 9001
    protocol websockets

    persistence true
    persistence_location /mosquitto/data/

    log_dest stdout
    log_type error
    log_type warning
    log_type notice

    allow_anonymous true
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mqtt
