# CouchDB's admin login and cluster secrets (values.yaml's extraSecretName).
apiVersion: v1
kind: Secret
metadata:
  name: obsidian-couchdb
  namespace: obsidian
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
data:
  adminPassword: ${OBSIDIAN_COUCHDB_ADMINPASSWORD}
  adminUsername: ${OBSIDIAN_COUCHDB_ADMINUSERNAME}
  cookieAuthSecret: ${OBSIDIAN_COUCHDB_COOKIEAUTHSECRET}
  erlangCookie: ${OBSIDIAN_COUCHDB_ERLANGCOOKIE}
