apiVersion: v1
kind: Secret
metadata:
  name: noip-duc-credentials
  namespace: noip-duc
  labels:
    app: noip-duc
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
data:
  NOIP_PASSWORD: ${NOIP_DUC_CREDENTIALS_NOIP_PASSWORD}
  NOIP_USERNAME: ${NOIP_DUC_CREDENTIALS_NOIP_USERNAME}
