apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret-grafana-admin.yaml
- secret-grafana-oidc.yaml
- secret-homeassistant-metrics.yaml
- secret-exportarr.yaml
- secret-garage-metrics.yaml
- secret-loki-s3.yaml
- secret-pihole-exporter.yaml
- secret-pve-exporter.yaml
- secret-qbittorrent-exporter.yaml
- pvc-grafana-data.yaml
