apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret-grafana-admin.yaml
- secret-grafana-oidc.yaml
- secret-loki-s3.yaml
- secret-pve-exporter.yaml
- pvc-grafana-data.yaml
