apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    homelab.local/category: apps
    homelab.local/data: database
    homelab.local/exposure: internet
    homelab.local/login: authentik-proxy
  name: babybuddy
spec:
  finalizers:
  - kubernetes
