apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    homelab.local/category: apps
  name: babybuddy
spec:
  finalizers:
  - kubernetes
