apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookshelf-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-retain-rwo
  resources:
    requests:
      storage: 2Gi
