apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret-key
  namespace: authentik
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
type: kubernetes.io/basic-auth
data:
  password: ${AUTHENTIK_SECRET_KEY_PASSWORD}
