apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitwarden-cli
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: external-secrets
      homelab.local/category: system
      homelab.local/env: prod
      homelab.local/managed-by: hand
  interval: 30m
  path: ./kubernetes/prod/system/external-secrets/bitwarden-cli/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: external-secrets
  # ClusterSecretStore is an external-secrets CRD.
  dependsOn:
  - name: external-secrets
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
      optional: true
    - kind: Secret
      name: cluster-secrets
      optional: true
