apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: babybuddy-server
  namespace: babybuddy
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: traefik
      podSelector:
        matchLabels:
          app.kubernetes.io/name: traefik
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: babybuddy-mcp
      podSelector:
        matchLabels:
          app: babybuddy-mcp
    ports:
    - port: 8000
      protocol: TCP
  podSelector:
    matchLabels:
      app: babybuddy
  policyTypes:
  - Ingress
